addons:
  postgresql: 9.6
  code_climate:
      repo_token: 58107d2379a29ee6287ba36f9b3c5698ddb390bd9b4c5258508a4faa4a5d6fd3
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.5.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - redis-server
